services:
  app:
    build: .
    ports:
      - 8080:8080
    secrets:
      - firebase-service-account
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/utopia
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      APP_SECURITY_CORS_ALLOWED_ORIGINS: http://localhost:4200
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-service-account
    depends_on:
      - db
  db:
    image: postgres:11.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=utopia
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
secrets:
  firebase-service-account:
    file: ../appendix/utopia-theatre-service-account.json
