spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/utopia
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
server:
  port: 8080
app:
  server:
    base-url: https://40fc-176-104-191-2.ngrok.io
  security:
    cors:
      allowed-origins: http://localhost:4200
  liqpay:
    public-key: ${APP_LIQPAY_PUBLIC_KEY}
    private-key: ${APP_LIQPAY_PRIVATE_KEY}
logging:
  level:
    org.hibernate.SQL: debug
