spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/utopia
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
server:
  port: 8080
app:
  security:
    cors:
      allowed-origins: http://localhost:4200
logging:
  level:
    org.hibernate.SQL: debug
