spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
server:
  port: ${PORT:8080}
app:
  server:
    base-url: ${APP_SERVER_BASE_URL}
  security:
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS}
  liqpay:
    public-key: ${APP_LIQPAY_PUBLIC_KEY}
    private-key: ${APP_LIQPAY_PRIVATE_KEY}
logging:
  level:
    org.hibernate.SQL: debug
